services:
  db:
    container_name: postgres_container_airbnb
    image: postgres   
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root_password
      POSTGRES_DB: airbnb
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4_container_airbnb
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: gangdb@admin.com
      PGADMIN_DEFAULT_PASSWORD: root_password
    ports:
      
      - "8085:80"

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php_container_airbnb
    restart: always
    volumes:
        - ../airbnb:/var/www/html
    ports:
        - "85:80"
        